// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJHClyIrpHfs5QNQD6vNl1bS-m1-TgvOQ',
    appId: '1:836929855785:android:36f44323b7e29ae1fc9738',
    messagingSenderId: '836929855785',
    projectId: 'pagadai-firebase',
    databaseURL: 'https://pagadai-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pagadai-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnadUOtsUJZnuZHog7wYfH0bLo2JgZ32Q',
    appId: '1:836929855785:ios:a327e43947389589fc9738',
    messagingSenderId: '836929855785',
    projectId: 'pagadai-firebase',
    databaseURL: 'https://pagadai-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pagadai-firebase.appspot.com',
    iosClientId: '836929855785-99cesdb0qrfi99krr64cibu8cqarhiqo.apps.googleusercontent.com',
    iosBundleId: 'com.sura.pagadai.pagadai',
  );
}
